version: '3.9'

services:

  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: on-failure
    healthcheck:
      test: "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'select 1;'"
      interval: 1s
      retries: 20
    volumes:
      - database_file_hierarchy_dev:/var/lib/postgresql/data
    networks:
      - file_hierarachy_dev
    ports:
      - "5432:5432"

volumes:
  database_file_hierarchy_dev:

networks:
  file_hierarachy_dev: